### ISSUE TITLE
og_facets

### ISSUE THREAD

**Issue by neilt1700** [d6lts/faceted_search#1]
I have updated the og_facets module so that it keeps working with this updated version of the faceted_search module: https://github.com/neilt1700/drupal6-updates

**Comment by dsnopek** [comment]
So, you're saying that the changes we made to faceted_search broke og_facets? What was breaking and what was the fix? It's not super clear from the commits on your repo.

**Comment by neilt1700** [comment]
Yes - the names of the constructor functions in faceted_search.inc had been changed from using the name of the class (deprecated) to `__construct` in faceted_search_facet and faceted_search_category. og_facets and og_facets_category classes were using these names to call parent constructors, i.e.:
`parent::faceted_search_facet('og', $active_path);`
and
`parent::faceted_search_category($count);`
Giving a fatal php error - method not found.
I changed these to:
`parent::__construct('og', $active_path);`
and
`parent::__construct($count);`

**Comment by srees** [comment]
Same thing occurs for cck_facets. Just corrected all the constructors to use the __construct format and it's golden again.

**Comment by dsnopek** [comment]
Thanks for the report! Unfortunately, we don't support either cck_facets or og_facets. If we did, we would make new forked versions of those modules and update them to use `__construct()` so they'd be PHP 7 and 8 compatible. However, since we don't, I'm going to close this issue.
